// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const GET_TIME_TABLE_LIST_REQUEST = 'GET_TIME_TABLE_LIST_REQUEST';
export const GET_TIME_TABLE_LIST_SUCCESS = 'GET_TIME_TABLE_LIST_SUCCESS';
export const GET_TIME_TABLE_LIST_FAILED = 'GET_TIME_TABLE_LIST_FAILED';

export const GET_TIME_TABLE_DETAIL_REQUEST = 'GET_TIME_TABLE_DETAIL_REQUEST';
export const GET_TIME_TABLE_DETAIL_SUCCESS = 'GET_TIME_TABLE_DETAIL_SUCCESS';
export const GET_TIME_TABLE_DETAIL_FAILED = 'GET_TIME_TABLE_DETAIL_FAILED';

export const GET_STATE_LIST_REQUEST = 'GET_STATE_LIST_REQUEST';
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS';
export const GET_STATE_LIST_FAILED = 'GET_STATE_LIST_FAILED';

export const GET_COUNTRY_LIST_REQUEST = 'GET_COUNTRY_LIST_REQUEST';
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS';
export const GET_COUNTRY_LIST_FAILED = 'GET_COUNTRY_LIST_FAILED';

export const FONT_SELECTION = 'FONT_SELECTION'
